version: '3.1'
services:
    ts-snack:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - APP_PORT=${APP_PORT}
        ports:
            - '${APP_PORT}:${APP_PORT}'
