version: '3'

services:
    snake:
        container_name: snake-container
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '5555:80'
        command: npm run serve
        volumes:
            - ./logs:/app/logs

    mongo:
        container_name: mongo-container
        image: mongo
        environment:
            MONGO_INITDB_DATABASE: toto
            MONGO_INITDB_ROOT_USERNAME: toto
            MONGO_INITDB_ROOT_PASSWORD: toto
        volumes:
            - ./data:/data/db
        ports:
            - '27017-27019:27017-27019'
